# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  allegro-artifactory:
    type: maven-repository
    url: https://artifactory.allegrogroup.com
    username: ${{ secrets.DEPENDABOT_ARTIFACTORY_USERNAME }}
    password: ${{ secrets.DEPENDABOT_ARTIFACTORY_PASSWORD }}

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - allegro-artifactory
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"