name: Publish

on: push

jobs:
  publish:
    name: Package, sign and publish the plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true

      - name: Verify plugin
        run: ./gradlew verifyPlugin